import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="" />
        <link rel="stylesheet" href="css/bootstrap.min.css" />
        {/* <link rel='stylesheet' href='../styles/scss/style.scss' /> */}
      </Head>
      <button className='btn btn-warning btn-sm'><h1 className='font-weight-light'>submit</h1></button>
    </div>
  )
}
